name: Release Builder

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 22
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'temurin'

    - name: Add PaperMC repository
      run: mvn dependency:purge-local-repository -DrepoUrl=https://repo.papermc.io/repository/maven-public/

    - name: Build with Maven
      run: mvn clean package -Dmaven.compiler.release=22

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/*.jar
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
